default:
    target: dev
    outputs:
        dev:
            type: snowflake
            account: nwse-dwh
            user: mehdi.lashgari@new-work.se
            role: BI_DBT
            authenticator: externalbrowser
            database: analytics
            warehouse: BI_DBT_WH_MEDIUM
            schema: TEST_MEHDI_LASHGARI
            threads: 4
            client_session_keep_alive: False
            connect_retries: 0
            connect_timeout: 10
            retry_on_database_errors: False
            retry_all: False
#            reuse_connections: False%  
