/*
    slimmed the query a lot to eliminate not that necessary (from training perspective) attributes
    target table: F_JOB_POSTING
*/
WITH
VISIBLE_POSTINGS AS
(
    SELECT
        v.POSTING_ID              as POSTING_ID,
        MIN(v.DAY_DATE)          as JOB_POSTING_FIRST_VISIBLE_DATE,
        MAX(v.DAY_DATE)         as JOB_POSTING_LAST_VISIBLE_DATE,
        COUNT(DISTINCT v.DAY_DATE) AS JOB_POSTING_TOTAL_VISIBLE_DAYS
    FROM
        RAW.PUBLIC.VISIBLE_POSTINGS_DAILY v
    GROUP BY
        v.POSTING_ID
),
PERFORMANCE_POSTINGS AS
(
    SELECT
        POSTING_ID AS POSTING_ID,
        DAY_DATE as JOB_POSTING_30DAY_VISIBILITY_DATE
    FROM
        (
            SELECT
                v.POSTING_ID AS POSTING_ID,
                v.DAY_DATE as DAY_DATE,
                ROW_NUMBER() OVER(PARTITION BY v.POSTING_ID ORDER BY v.DAY_DATE ASC) AS k
            FROM
                RAW.PUBLIC.VISIBLE_POSTINGS_DAILY v
        ) x
    WHERE
        k = 30
)
SELECT
    pst.ID AS JOB_POSTING_CODE,
    CASE WHEN h.POSTING_ID IS NOT NULL THEN 'Top paid' WHEN pst.paid = 1 THEN 'Low paid' ELSE 'Unpaid' END AS JOB_POSTING_PAID_TYPE,
    COALESCE(pst.CREATED_AT, TO_DATE('19000101', 'YYYYMMDD')) AS JOB_POSTING_CREATION_DATETIME,
    pst.ACTIVE_UNTIL AS JOB_POSTING_EXPIRATION_DATETIME,
    COALESCE(usr.USER_ID, 0) AS JOB_POSTING_EDITOR_USER_ID,
    pst.ORDER_ID AS JOB_POSTING_ORDER_ID, 
    pst."state" AS JOB_POSTING_STATUS,
    pst.COMPANY_ID as JOB_POSTING_COMPANY_ID,
    pst.COMPANY_NAME as JOB_POSTING_COMPANY_NAME,
    JOB_POSTING_FIRST_VISIBLE_DATE,
    JOB_POSTING_LAST_VISIBLE_DATE,
    JOB_POSTING_TOTAL_VISIBLE_DAYS,
    JOB_POSTING_30DAY_VISIBILITY_DATE,
    COALESCE(pst.SKILLS, 'Unknown') AS JOB_POSTING_SKILLS,
    pst."function" AS JOB_POSTING_JOB_TITLE,
    pst.ACTIVATED_AT AS JOB_POSTING_ACTIVATION_DATETIME,
    UPPER(pst.COUNTRY) AS JOB_POSTING_COUNTRY,
    pst.CITY AS JOB_POSTING_STATE,
    pst.REGION AS JOB_POSTING_CITY,
    pst.ZIPCODE AS JOB_POSTING_ZIPCODE,
    CASE WHEN pst."state" IN (3,4,5) THEN pst.ACTIVE_UNTIL ELSE NULL END AS JOB_POSTING_DEACTIVATION_DATETIME, 
    pst.JOB_CODE AS JOB_POSTING_CODE_FROM_EDITOR,
    CASE WHEN pst.EDITOR_ID = 13521795 THEN TRUE ELSE FALSE END AS IS_JOB_POSTING_CREATED_BY_JOBWARE,
    COALESCE(pst.TAGS, 'Unknown') as JOB_POSTING_TAGS,
    CASE
        WHEN pst."state" IN (3,4,5) THEN datediff(day, ACTIVATED_AT, ACTIVE_UNTIL)
        WHEN pst."state" IN (1,2)   THEN datediff(day, ACTIVATED_AT, current_date)
        ELSE 0
    END as JOB_POSTING_RUNNING_TIME_DAYS
FROM
    RAW.PUBLIC.POSTINGS pst
    LEFT JOIN RAW.PUBLIC.LU_USER usr ON pst.EDITOR_ID = usr.USER_ID
    LEFT JOIN RAW.PUBLIC.FCT_HIGH_REVENUE_POSTINGS h ON pst.ID = h.POSTING_ID
    LEFT JOIN VISIBLE_POSTINGS vp ON pst.ID = vp.POSTING_ID
    LEFT JOIN PERFORMANCE_POSTINGS b ON pst.ID = b.POSTING_ID
where
    to_date(pst.created_at) = to_date('20220202','YYYYMMDD')
limit 10
;